In [1]:
import numpy as np

<pre>
Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.
</pre>

In [7]:
def generate_Alex_Theo_Vand(vector, cols, increasing=True):
    op_matrix = []
    if not increasing:
        for x in vector:
            for i in range(cols):
                op_matrix.append(x ** (cols - 1 - i))
        return np.array(op_matrix).reshape(vector.size, cols)
    else:
        for x in vector:
            for i in range(cols):
                op_matrix.append(x ** i)
        return np.array(op_matrix).reshape(vector.size, cols)
        
    

vector = np.array([9, 5, 10, 14, 15])
cols = 3
output_mat_decreasing = generate_Alex_Theo_Vand(
vector, cols, False
)

output_mat_increasing = generate_Alex_Theo_Vand(
vector, cols, True
)

print(f"The input matrix is {vector}")
print(f"The number of cols is {cols}")
print("When In Decreasing order......................")
print(output_mat_decreasing)
print("When In Increasing order......................")
print(output_mat_increasing)

The input matrix is [ 9  5 10 14 15]
The number of cols is 3
When In Decreasing order......................
[[ 81   9   1]
 [ 25   5   1]
 [100  10   1]
 [196  14   1]
 [225  15   1]]
When In Increasing order......................
[[  1   9  81]
 [  1   5  25]
 [  1  10 100]
 [  1  14 196]
 [  1  15 225]]


<pre>
Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
</pre>

In [34]:
def find_moving_Average(array, k):
    i = 0
    averages = []
    
    while i <  len(array) - k + 1:
        current_window = array[i: i + k]
        #print(current_window)
        average = sum(current_window) / k
        averages.append(average)
        i = i + 1
    return np.array(averages)


array = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k = 3
averages_ = find_moving_Average(array, k)
print(f"The Given input is {array}")
print("================================")
for i in range(len(averages_)):
    print(f"The moving average of y{i + 1} is {averages_[i]}")


The Given input is [  3   5   7   2   8  10  11  65  72  81  99 100 150]
The moving average of y1 is 5.0
The moving average of y2 is 4.666666666666667
The moving average of y3 is 5.666666666666667
The moving average of y4 is 6.666666666666667
The moving average of y5 is 9.666666666666666
The moving average of y6 is 28.666666666666668
The moving average of y7 is 49.333333333333336
The moving average of y8 is 72.66666666666667
The moving average of y9 is 84.0
The moving average of y10 is 93.33333333333333
The moving average of y11 is 116.33333333333333
